const fs = require('fs');
const path = require('path');

const {
  IOSConfig,
  withAppDelegate,
  withInfoPlist,
  withXcodeProject,
} = require('expo/config-plugins');

/**
 * Links the Live Activity's shared Swift into the *app* target.
 *
 * `@bacons/apple-targets` builds the widget extension from `targets/widget`, but
 * three of those files have to exist in the app target too:
 *
 *   - the `LiveActivityIntent`s, because the system only performs an intent in
 *     the app's process when Xcode's App Intents metadata extractor finds it in
 *     the app target's own sources (a pod's static-library sources are not
 *     scanned — which is why this cannot live in `modules/loopcam-recorder`);
 *   - `LoopCamActivityAttributes`, because ActivityKit pairs an activity with
 *     its presentation by that type's name, so both sides need the same shape;
 *   - `LoopCamLiveActivityHost`, which is what actually requests, updates and
 *     ends the activity, and is registered from `AppDelegate` below.
 *
 * `ios/` is regenerated by prebuild, so the files are copied in and added to the
 * Sources phase on every run rather than committed.
 */
const SHARED_DIR = path.join('targets', 'widget', 'Shared');
const GROUP_NAME = 'LiveActivity';

/** The whole feature is off if `AppDelegate` never registers the host. */
const REGISTER_CALL = 'LoopCamLiveActivityHost.shared.register()';
const APP_DELEGATE_ANCHOR =
  'return super.application(application, didFinishLaunchingWithOptions: launchOptions)';

function withSharedSources(config) {
  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const projectRoot = cfg.modRequest.projectRoot;
    const platformRoot = cfg.modRequest.platformProjectRoot;
    const appName = cfg.modRequest.projectName;

    const source = path.join(projectRoot, SHARED_DIR);
    if (!fs.existsSync(source)) {
      throw new Error(`[loopcam-live-activity] Missing ${SHARED_DIR}`);
    }

    const destination = path.join(platformRoot, appName, GROUP_NAME);
    fs.mkdirSync(destination, { recursive: true });

    const files = fs.readdirSync(source).filter((file) => file.endsWith('.swift'));
    if (files.length === 0) {
      throw new Error(`[loopcam-live-activity] No Swift files in ${SHARED_DIR}`);
    }

    for (const file of files) {
      fs.copyFileSync(path.join(source, file), path.join(destination, file));

      const groupPath = `${appName}/${GROUP_NAME}`;
      IOSConfig.XcodeUtils.ensureGroupRecursively(project, groupPath);
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath: `${groupPath}/${file}`,
        groupName: groupPath,
        project,
      });
    }

    return cfg;
  });
}

function withLiveActivitySupport(config) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.NSSupportsLiveActivities = true;
    // The card is repainted on every clip boundary — with a short clip length
    // (§2.1 allows 5 s) that counts as frequent, and without this the system
    // starts dropping updates partway through a session.
    cfg.modResults.NSSupportsLiveActivitiesFrequentUpdates = true;
    return cfg;
  });
}

function withHostRegistration(config) {
  return withAppDelegate(config, (cfg) => {
    const contents = cfg.modResults.contents;
    if (contents.includes(REGISTER_CALL)) return cfg;

    if (!contents.includes(APP_DELEGATE_ANCHOR)) {
      throw new Error(
        '[loopcam-live-activity] Could not find the didFinishLaunching return in AppDelegate.swift; ' +
          `add \`${REGISTER_CALL}\` by hand or update this plugin.`
      );
    }

    cfg.modResults.contents = contents.replace(
      APP_DELEGATE_ANCHOR,
      `// Lock Screen Live Activity (§5.2) — added by plugins/withLoopCamLiveActivity.js\n    ${REGISTER_CALL}\n\n    ${APP_DELEGATE_ANCHOR}`
    );
    return cfg;
  });
}

module.exports = function withLoopCamLiveActivity(config) {
  return withHostRegistration(withSharedSources(withLiveActivitySupport(config)));
};
