const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * Signs release builds with the committed `LoopCam.keystore`.
 *
 * `android/` is regenerated by prebuild and not committed, so the stock
 * template's `signingConfigs` — which signs release with the *debug* key — comes
 * back every time. This re-injects a real release config on each run.
 *
 * The keystore file is in the repo; its passwords are not, and must not be: the
 * repo is public, so a committed password would make the key trivially usable by
 * anyone. Supply them per machine, either as environment variables or as Gradle
 * properties in `~/.gradle/gradle.properties` (outside the repo):
 *
 *   LOOPCAM_KEYSTORE_PASSWORD   store password
 *   LOOPCAM_KEY_ALIAS           alias of the key inside the store
 *   LOOPCAM_KEY_PASSWORD        key password (defaults to the store password)
 *
 * Gradle resolves these lazily, so debug builds still work with none of them set
 * — only an actual release build fails, and it fails at signing with a clear
 * message rather than silently producing a debug-signed APK.
 */
const KEYSTORE = 'LoopCam.keystore';

/** `rootProject` is `android/`, so `../` is the repo root. */
const RELEASE_SIGNING_CONFIG = `        release {
            storeFile rootProject.file('../${KEYSTORE}')
            storePassword findProperty('LOOPCAM_KEYSTORE_PASSWORD') ?: System.getenv('LOOPCAM_KEYSTORE_PASSWORD')
            keyAlias findProperty('LOOPCAM_KEY_ALIAS') ?: System.getenv('LOOPCAM_KEY_ALIAS')
            keyPassword findProperty('LOOPCAM_KEY_PASSWORD') ?: System.getenv('LOOPCAM_KEY_PASSWORD') ?: findProperty('LOOPCAM_KEYSTORE_PASSWORD') ?: System.getenv('LOOPCAM_KEYSTORE_PASSWORD')
        }
`;

const SIGNING_CONFIGS_ANCHOR = 'signingConfigs {';

/** What the template ships: release reuses the debug key. */
const DEBUG_SIGNED_RELEASE = 'signingConfig signingConfigs.debug';
const RELEASE_BUILD_TYPE = /(buildTypes\s*\{[\s\S]*?release\s*\{)([\s\S]*?)(\n\s*\})/;

module.exports = function withAndroidSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        `[android-signing] Expected a Groovy app/build.gradle, got ${cfg.modResults.language}; update this plugin.`
      );
    }

    let contents = cfg.modResults.contents;
    if (contents.includes(KEYSTORE)) return cfg;

    if (!contents.includes(SIGNING_CONFIGS_ANCHOR)) {
      throw new Error(
        '[android-signing] No `signingConfigs {` block in app/build.gradle; the template changed.'
      );
    }
    contents = contents.replace(
      SIGNING_CONFIGS_ANCHOR,
      `${SIGNING_CONFIGS_ANCHOR}\n${RELEASE_SIGNING_CONFIG}`
    );

    // Point the release build type at the config added above. Scoped to the
    // release block so the debug build type keeps its own debug signing.
    const match = contents.match(RELEASE_BUILD_TYPE);
    if (!match || !match[2].includes(DEBUG_SIGNED_RELEASE)) {
      throw new Error(
        '[android-signing] Could not find `signingConfig signingConfigs.debug` in the release ' +
          'buildType; release builds would ship debug-signed. Update this plugin.'
      );
    }
    contents = contents.replace(
      RELEASE_BUILD_TYPE,
      (_, open, body, close) =>
        open + body.replace(DEBUG_SIGNED_RELEASE, 'signingConfig signingConfigs.release') + close
    );

    cfg.modResults.contents = contents;
    return cfg;
  });
};
